// ===== School-Level Course Data =====
export const SCHOOL_COURSES = [
  // ── Mathematics ──
  { id:'s-math-foundation', subject:'Mathematics', name:'Foundation Mathematics Course', icon:'🔢', color:'#3b82f6',
    description:'Build a strong base in numbers, fractions, decimals and basic operations.',
    topics:[
      {id:'smf1',name:'Number Systems',notes:'<p><strong>Number Systems</strong> include Natural numbers, Whole numbers, Integers, Rational and Irrational numbers. Understanding classifications is key to all of mathematics.</p><p>• Natural Numbers (1,2,3…) • Whole Numbers (0,1,2…) • Integers (…-2,-1,0,1,2…) • Rational (p/q form) • Irrational (√2, π)</p>'},
      {id:'smf2',name:'Fractions & Decimals',notes:'<p><strong>Fractions</strong> represent parts of a whole. Operations include addition, subtraction, multiplication and division of fractions. Decimals are another representation of fractions with base 10.</p>'},
      {id:'smf3',name:'LCM & HCF',notes:'<p><strong>LCM</strong> (Least Common Multiple) and <strong>HCF</strong> (Highest Common Factor) are fundamental for simplifying fractions and solving problems involving ratios.</p>'},
      {id:'smf4',name:'Ratio & Proportion',notes:'<p><strong>Ratio</strong> compares two quantities. <strong>Proportion</strong> states two ratios are equal. Used extensively in real-world problem solving.</p>'},
      {id:'smf5',name:'Percentages',notes:'<p><strong>Percentage</strong> means "per hundred". Key formulas: Percentage = (Part/Whole)×100. Applications include discounts, profit/loss, and interest calculations.</p>'},
      {id:'smf6',name:'Profit, Loss & Interest',notes:'<p>Profit = SP - CP. Loss = CP - SP. <strong>Simple Interest</strong> = PRT/100. <strong>Compound Interest</strong> = P(1+R/100)^T - P.</p>'},
    ]},
  { id:'s-math-algebra', subject:'Mathematics', name:'Algebra Mastery Course', icon:'📐', color:'#3b82f6',
    description:'Master algebraic expressions, equations and polynomials.',
    topics:[
      {id:'sma1',name:'Variables & Expressions',notes:'<p>Variables are symbols representing unknown values. <strong>Algebraic expressions</strong> combine variables, constants and operators. Like terms can be combined.</p>'},
      {id:'sma2',name:'Linear Equations',notes:'<p>Equations of the form ax + b = 0. Solve by isolating the variable. Applications include age problems, distance problems, and mixture problems.</p>'},
      {id:'sma3',name:'Quadratic Equations',notes:'<p>Form: ax² + bx + c = 0. Solutions via factoring, completing the square, or the quadratic formula: x = (-b ± √(b²-4ac)) / 2a.</p>'},
      {id:'sma4',name:'Polynomials',notes:'<p>Expressions with multiple terms. Degree = highest power. Operations include addition, subtraction, multiplication, and division of polynomials.</p>'},
      {id:'sma5',name:'Factorization',notes:'<p>Breaking expressions into products. Methods: common factor, grouping, identities (a²-b²), (a+b)², (a-b)². Essential for simplification.</p>'},
      {id:'sma6',name:'Inequalities',notes:'<p>Statements comparing expressions with <, >, ≤, ≥. Solve like equations but flip the sign when multiplying/dividing by negatives.</p>'},
    ]},
  { id:'s-math-geometry', subject:'Mathematics', name:'Geometry Complete Course', icon:'📏', color:'#3b82f6',
    description:'Lines, angles, triangles, circles and coordinate geometry.',
    topics:[
      {id:'smg1',name:'Lines & Angles',notes:'<p>Types of angles: acute, obtuse, right, straight, reflex. Parallel lines cut by a transversal create corresponding, alternate and co-interior angles.</p>'},
      {id:'smg2',name:'Triangles',notes:'<p>Sum of angles = 180°. Types: equilateral, isosceles, scalene. Congruence: SSS, SAS, ASA, RHS. Area = ½ × base × height.</p>'},
      {id:'smg3',name:'Quadrilaterals',notes:'<p>Four-sided polygons. Types include parallelogram, rectangle, square, rhombus, trapezium. Sum of angles = 360°.</p>'},
      {id:'smg4',name:'Circles',notes:'<p>Key terms: radius, diameter, chord, arc, sector. Circumference = 2πr. Area = πr². Theorems on tangents and chords.</p>'},
      {id:'smg5',name:'Area & Perimeter',notes:'<p>Formulas for rectangles, triangles, circles, trapeziums. Composite shapes break into simpler parts.</p>'},
      {id:'smg6',name:'Coordinate Geometry',notes:'<p>Plotting points on (x,y) plane. Distance formula, midpoint formula, slope, equation of a line (y = mx + c).</p>'},
    ]},
  { id:'s-math-trig', subject:'Mathematics', name:'Trigonometry Starter Course', icon:'📊', color:'#3b82f6',
    description:'Sin, cos, tan and their applications in triangles.',
    topics:[
      {id:'smt1',name:'Trigonometric Ratios',notes:'<p>sin θ = Opposite/Hypotenuse, cos θ = Adjacent/Hypotenuse, tan θ = Opposite/Adjacent. Remember: SOH-CAH-TOA.</p>'},
      {id:'smt2',name:'Standard Angles',notes:'<p>Values at 0°, 30°, 45°, 60°, 90°. sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1. Build the standard table.</p>'},
      {id:'smt3',name:'Trigonometric Identities',notes:'<p>sin²θ + cos²θ = 1, 1 + tan²θ = sec²θ, 1 + cot²θ = cosec²θ. Used to simplify and prove results.</p>'},
      {id:'smt4',name:'Heights & Distances',notes:'<p>Applications of trig: angle of elevation, angle of depression. Solve real-world problems using tan, sin, cos.</p>'},
      {id:'smt5',name:'Trigonometric Equations',notes:'<p>Solving equations like sin x = 1/2 for general solutions. Understanding periodicity and principal values.</p>'},
    ]},
  { id:'s-math-stats', subject:'Mathematics', name:'Probability & Statistics Course', icon:'🎲', color:'#3b82f6',
    description:'Data analysis, probability and statistical measures.',
    topics:[
      {id:'sms1',name:'Data Collection & Representation',notes:'<p>Types: primary/secondary data. Representations: bar graphs, histograms, pie charts, frequency polygons.</p>'},
      {id:'sms2',name:'Mean, Median & Mode',notes:'<p>Mean = sum/count. Median = middle value. Mode = most frequent. Grouped data uses class intervals.</p>'},
      {id:'sms3',name:'Probability Basics',notes:'<p>P(E) = Favorable outcomes / Total outcomes. 0 ≤ P(E) ≤ 1. P(E) + P(not E) = 1. Coin, dice, card problems.</p>'},
      {id:'sms4',name:'Standard Deviation & Variance',notes:'<p>Variance measures spread. SD = √Variance. Low SD = data clustered near mean. High SD = data spread out.</p>'},
      {id:'sms5',name:'Combinatorics Intro',notes:'<p>Permutations (order matters): nPr = n!/(n-r)!. Combinations (order doesn\'t matter): nCr = n!/r!(n-r)!.</p>'},
    ]},
  { id:'s-math-advanced', subject:'Mathematics', name:'Advanced Problem Solving Course', icon:'🧠', color:'#3b82f6',
    description:'Challenging problems, olympiad prep and logical reasoning.',
    topics:[
      {id:'sma_1',name:'Number Theory',notes:'<p>Divisibility rules, prime factorization, Euler\'s totient, modular arithmetic. Foundation for competition math.</p>'},
      {id:'sma_2',name:'Sequences & Series',notes:'<p>AP: a, a+d, a+2d... Sum = n/2(2a+(n-1)d). GP: a, ar, ar²... Sum = a(rⁿ-1)/(r-1).</p>'},
      {id:'sma_3',name:'Logical Reasoning',notes:'<p>Pattern recognition, deductive reasoning, puzzles. Strengthens analytical thinking and problem-solving.</p>'},
      {id:'sma_4',name:'Mathematical Induction',notes:'<p>Prove base case, assume for k, prove for k+1. Powerful technique for proving statements for all natural numbers.</p>'},
      {id:'sma_5',name:'Sets & Venn Diagrams',notes:'<p>Union, intersection, complement. Venn diagrams visualize relationships. n(A∪B) = n(A)+n(B)-n(A∩B).</p>'},
    ]},

  // ── Physics ──
  { id:'s-phys-basics', subject:'Physics', name:'Basics of Physics Course', icon:'⚡', color:'#f59e0b',
    description:'Fundamental concepts: units, measurements, and motion.',
    topics:[
      {id:'spb1',name:'Units & Measurements',notes:'<p>SI units: meter, kilogram, second. Derived units. Significant figures. Dimensional analysis for unit conversions.</p>'},
      {id:'spb2',name:'Scalars & Vectors',notes:'<p>Scalars have magnitude only (speed, mass). Vectors have magnitude and direction (velocity, force). Vector addition: triangle and parallelogram law.</p>'},
      {id:'spb3',name:'Motion in a Straight Line',notes:'<p>Distance vs displacement. Speed vs velocity. Acceleration. Equations: v=u+at, s=ut+½at², v²=u²+2as.</p>'},
      {id:'spb4',name:'Laws of Motion',notes:'<p>Newton\'s First Law (inertia), Second Law (F=ma), Third Law (action-reaction). Free body diagrams. Friction.</p>'},
      {id:'spb5',name:'Gravitation',notes:'<p>F = Gm₁m₂/r². Acceleration due to gravity g = 9.8 m/s². Weight vs Mass. Free fall and projectile motion.</p>'},
    ]},
  { id:'s-phys-mechanics', subject:'Physics', name:'Mechanics Fundamentals Course', icon:'⚙️', color:'#f59e0b',
    description:'Work, energy, power, and rotational motion.',
    topics:[
      {id:'spm1',name:'Work & Energy',notes:'<p>Work = Force × displacement × cos θ. KE = ½mv². PE = mgh. Conservation of energy. Work-energy theorem.</p>'},
      {id:'spm2',name:'Power',notes:'<p>Power = Work/Time = Force × velocity. SI unit: Watt. 1 HP = 746 W. Efficiency = useful output/input × 100%.</p>'},
      {id:'spm3',name:'Momentum & Collisions',notes:'<p>p = mv. Conservation of momentum. Elastic (KE conserved) vs inelastic collisions. Impulse = FΔt = Δp.</p>'},
      {id:'spm4',name:'Circular Motion',notes:'<p>Centripetal acceleration = v²/r. Centripetal force = mv²/r. Applications: banking, satellites, loops.</p>'},
      {id:'spm5',name:'Simple Machines',notes:'<p>Lever, pulley, inclined plane, screw, wedge, wheel-axle. Mechanical advantage = Load/Effort. Efficiency.</p>'},
    ]},
  { id:'s-phys-em', subject:'Physics', name:'Electricity & Magnetism Course', icon:'🔌', color:'#f59e0b',
    description:'Electric circuits, magnetism and electromagnetic induction.',
    topics:[
      {id:'spe1',name:'Electric Charge & Current',notes:'<p>Charge: property of matter. Current I = Q/t. Conductors vs Insulators. Coulomb\'s law: F = kq₁q₂/r².</p>'},
      {id:'spe2',name:'Ohm\'s Law & Circuits',notes:'<p>V = IR. Resistance. Series: R_total = R₁+R₂. Parallel: 1/R = 1/R₁+1/R₂. Kirchhoff\'s laws.</p>'},
      {id:'spe3',name:'Magnetic Effects',notes:'<p>Magnetic field around current-carrying wire. Electromagnets. Fleming\'s left-hand rule. DC motor.</p>'},
      {id:'spe4',name:'Electromagnetic Induction',notes:'<p>Faraday\'s law: EMF = -dΦ/dt. Lenz\'s law. AC generator. Transformers: V₁/V₂ = N₁/N₂.</p>'},
      {id:'spe5',name:'Household Electricity',notes:'<p>AC vs DC. Fuses and circuit breakers. Earthing. Power: P = VI = I²R. Units: kWh (electricity bill).</p>'},
    ]},
  { id:'s-phys-light', subject:'Physics', name:'Light & Optics Course', icon:'💡', color:'#f59e0b',
    description:'Reflection, refraction, lenses and the human eye.',
    topics:[
      {id:'spl1',name:'Reflection of Light',notes:'<p>Laws of reflection. Plane mirrors: virtual, erect, same-size image. Concave & convex mirrors. Mirror formula: 1/f = 1/v + 1/u.</p>'},
      {id:'spl2',name:'Refraction of Light',notes:'<p>Snell\'s law: n₁ sin i = n₂ sin r. Refractive index. Total internal reflection. Real/apparent depth.</p>'},
      {id:'spl3',name:'Lenses',notes:'<p>Convex (converging) and concave (diverging) lenses. Lens formula: 1/f = 1/v - 1/u. Power P = 1/f (diopters).</p>'},
      {id:'spl4',name:'Dispersion & Spectrum',notes:'<p>White light splits into VIBGYOR through a prism. Rainbow formation. Scattering of light (blue sky, red sunset).</p>'},
      {id:'spl5',name:'Human Eye & Defects',notes:'<p>Parts: cornea, iris, lens, retina. Defects: myopia (concave lens), hypermetropia (convex lens), presbyopia.</p>'},
    ]},
  { id:'s-phys-heat', subject:'Physics', name:'Heat & Thermodynamics Course', icon:'🌡️', color:'#f59e0b',
    description:'Temperature, heat transfer and laws of thermodynamics.',
    topics:[
      {id:'sph1',name:'Temperature & Heat',notes:'<p>Temperature: degree of hotness. Heat: energy transfer. Scales: Celsius, Fahrenheit, Kelvin. C/5 = (F-32)/9.</p>'},
      {id:'sph2',name:'Thermal Expansion',notes:'<p>Solids: linear, area, volume expansion. Liquids: anomalous expansion of water. Applications in daily life.</p>'},
      {id:'sph3',name:'Heat Transfer',notes:'<p>Conduction (solids), Convection (fluids), Radiation (no medium). Conductors vs insulators. Thermos flask.</p>'},
      {id:'sph4',name:'Specific Heat & Calorimetry',notes:'<p>Q = mcΔT. Specific heat capacity. Calorimetry principle: heat lost = heat gained. Latent heat of fusion/vaporization.</p>'},
      {id:'sph5',name:'Laws of Thermodynamics',notes:'<p>Zeroth law (thermal equilibrium), First law (ΔU = Q - W), Second law (entropy always increases), Third law.</p>'},
    ]},

  // ── Chemistry ──
  { id:'s-chem-basic', subject:'Chemistry', name:'Basic Chemistry Course', icon:'🧪', color:'#22c55e',
    description:'Atoms, molecules, elements and chemical bonding.',
    topics:[
      {id:'scb1',name:'Matter & Its Classification',notes:'<p>States: solid, liquid, gas. Pure substances (elements, compounds) vs mixtures (homogeneous, heterogeneous). Separation techniques.</p>'},
      {id:'scb2',name:'Atomic Structure',notes:'<p>Subatomic particles: protons (+), neutrons (0), electrons (-). Atomic number Z, mass number A. Bohr model. Electron configurations.</p>'},
      {id:'scb3',name:'Chemical Bonding',notes:'<p>Ionic bonds (transfer of electrons), Covalent bonds (sharing electrons), Metallic bonds. Electronegativity. Lewis dot structures.</p>'},
      {id:'scb4',name:'Elements & Symbols',notes:'<p>118 elements. Symbols from Latin/English names. Metals, non-metals, metalloids. Physical and chemical properties.</p>'},
      {id:'scb5',name:'Valency & Chemical Formulas',notes:'<p>Valency: combining capacity. Writing formulas using criss-cross method. Molecular vs empirical formulas.</p>'},
    ]},
  { id:'s-chem-organic', subject:'Chemistry', name:'Organic Chemistry Starter Course', icon:'⬡', color:'#22c55e',
    description:'Carbon compounds, hydrocarbons and functional groups.',
    topics:[
      {id:'sco1',name:'Carbon & Its Compounds',notes:'<p>Carbon: tetravalent, forms catenation. Allotropes: diamond, graphite, fullerene. Organic vs inorganic compounds.</p>'},
      {id:'sco2',name:'Hydrocarbons',notes:'<p>Alkanes (CₙH₂ₙ₊₂), Alkenes (CₙH₂ₙ), Alkynes (CₙH₂ₙ₋₂). Naming conventions (IUPAC). Structural isomers.</p>'},
      {id:'sco3',name:'Functional Groups',notes:'<p>Alcohol (-OH), Aldehyde (-CHO), Ketone (C=O), Carboxylic acid (-COOH), Amine (-NH₂). Each gives characteristic reactions.</p>'},
      {id:'sco4',name:'Nomenclature (IUPAC)',notes:'<p>Rules: find longest chain, number carbons, name substituents, combine with prefixes/suffixes. Practice with examples.</p>'},
      {id:'sco5',name:'Polymers & Biomolecules',notes:'<p>Addition and condensation polymers. Carbohydrates, proteins, fats, nucleic acids. Natural vs synthetic polymers.</p>'},
    ]},
  { id:'s-chem-inorganic', subject:'Chemistry', name:'Inorganic Chemistry Course', icon:'🔬', color:'#22c55e',
    description:'Metals, non-metals, salts and extraction processes.',
    topics:[
      {id:'sci1',name:'Metals & Non-Metals',notes:'<p>Metals: lustrous, malleable, ductile, good conductors. Non-metals: brittle, poor conductors. Metalloids share properties.</p>'},
      {id:'sci2',name:'Reactivity Series',notes:'<p>K > Na > Ca > Mg > Al > Zn > Fe > Cu > Ag > Au. More reactive metals displace less reactive ones from solutions.</p>'},
      {id:'sci3',name:'Extraction of Metals',notes:'<p>Highly reactive: electrolysis. Medium: reduction with carbon. Low: self-reduction. Refining: electrolytic refining.</p>'},
      {id:'sci4',name:'Acids, Bases & Salts',notes:'<p>Acids: H⁺ ions, sour. Bases: OH⁻ ions, bitter. pH scale 0-14. Neutralization: Acid + Base → Salt + Water.</p>'},
      {id:'sci5',name:'Corrosion & Prevention',notes:'<p>Rusting: iron + oxygen + water. Prevention: painting, galvanizing, alloying, cathodic protection, oiling.</p>'},
    ]},
  { id:'s-chem-reactions', subject:'Chemistry', name:'Chemical Reactions Course', icon:'⚗️', color:'#22c55e',
    description:'Types of reactions, balancing equations and stoichiometry.',
    topics:[
      {id:'scr1',name:'Types of Reactions',notes:'<p>Combination, Decomposition, Displacement, Double displacement, Redox reactions. Identify by analyzing reactants/products.</p>'},
      {id:'scr2',name:'Balancing Equations',notes:'<p>Law of conservation of mass. Balance by adjusting coefficients. Hit-and-trial method. Steps: list elements, balance one at a time.</p>'},
      {id:'scr3',name:'Oxidation & Reduction',notes:'<p>Oxidation: loss of electrons / gain of oxygen. Reduction: gain of electrons / loss of oxygen. Oxidizing and reducing agents.</p>'},
      {id:'scr4',name:'Stoichiometry',notes:'<p>Mole concept: 1 mole = 6.022×10²³ particles. Molar mass. Using balanced equations to find reactant/product quantities.</p>'},
      {id:'scr5',name:'Rate of Reactions',notes:'<p>Factors: concentration, temperature, surface area, catalyst. Collision theory. Activation energy. Exothermic vs endothermic.</p>'},
    ]},
  { id:'s-chem-pt', subject:'Chemistry', name:'Periodic Table Mastery Course', icon:'📋', color:'#22c55e',
    description:'Periodic trends, groups, periods and element properties.',
    topics:[
      {id:'scp1',name:'History of Periodic Table',notes:'<p>Döbereiner\'s triads → Newlands\' octaves → Mendeleev\'s table → Modern periodic table (based on atomic number).</p>'},
      {id:'scp2',name:'Groups & Periods',notes:'<p>18 groups (vertical), 7 periods (horizontal). Group 1: alkali metals. Group 17: halogens. Group 18: noble gases.</p>'},
      {id:'scp3',name:'Periodic Trends',notes:'<p>Atomic radius: decreases across period, increases down group. Ionization energy: opposite. Electronegativity: increases across.</p>'},
      {id:'scp4',name:'Transition Elements',notes:'<p>d-block elements. Variable oxidation states, colored compounds, catalytic activity. Examples: Fe, Cu, Zn, Mn.</p>'},
      {id:'scp5',name:'Chemical Families',notes:'<p>Alkali metals (reactive), Alkaline earth, Halogens (reactive non-metals), Noble gases (inert), Lanthanides & Actinides.</p>'},
    ]},

  // ── Biology ──
  { id:'s-bio-human', subject:'Biology', name:'Human Biology Course', icon:'🫀', color:'#ec4899',
    description:'Body systems, nutrition, and health.',
    topics:[
      {id:'sbh1',name:'Digestive System',notes:'<p>Mouth → Esophagus → Stomach → Small intestine → Large intestine. Enzymes: amylase, pepsin, lipase. Absorption in villi.</p>'},
      {id:'sbh2',name:'Circulatory System',notes:'<p>Heart: 4 chambers. Arteries (oxygen-rich), Veins (oxygen-poor), Capillaries. Blood: RBCs, WBCs, platelets, plasma.</p>'},
      {id:'sbh3',name:'Respiratory System',notes:'<p>Nose → Pharynx → Larynx → Trachea → Bronchi → Lungs (alveoli). Gas exchange: O₂ in, CO₂ out. Breathing mechanism.</p>'},
      {id:'sbh4',name:'Nervous System',notes:'<p>CNS (brain, spinal cord) + PNS. Neurons: dendrite → cell body → axon. Reflex arc. Sensory and motor neurons.</p>'},
      {id:'sbh5',name:'Excretory System',notes:'<p>Kidneys filter blood → urine. Nephron: glomerulus → tubule → collecting duct. Dialysis for kidney failure.</p>'},
      {id:'sbh6',name:'Nutrition & Health',notes:'<p>Carbohydrates, proteins, fats, vitamins, minerals, water. Balanced diet. Deficiency diseases. BMI and calorie needs.</p>'},
    ]},
  { id:'s-bio-plant', subject:'Biology', name:'Plant Biology Course', icon:'🌿', color:'#ec4899',
    description:'Photosynthesis, plant systems and reproduction.',
    topics:[
      {id:'sbp1',name:'Photosynthesis',notes:'<p>6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. Light-dependent (thylakoids) and light-independent (stroma) reactions. Chlorophyll captures light.</p>'},
      {id:'sbp2',name:'Plant Transport',notes:'<p>Xylem: water + minerals upward (transpiration pull). Phloem: food transport (translocation). Root pressure.</p>'},
      {id:'sbp3',name:'Plant Reproduction',notes:'<p>Asexual: budding, fragmentation, spore formation. Sexual: pollination → fertilization → seed formation. Flower parts.</p>'},
      {id:'sbp4',name:'Plant Hormones',notes:'<p>Auxins (growth), Gibberellins (stem elongation), Cytokinins (cell division), Abscisic acid (dormancy), Ethylene (ripening).</p>'},
      {id:'sbp5',name:'Plant Tissues',notes:'<p>Meristematic (dividing) and Permanent tissues. Xylem, phloem, parenchyma, collenchyma, sclerenchyma.</p>'},
    ]},
  { id:'s-bio-genetics', subject:'Biology', name:'Genetics & Evolution Course', icon:'🧬', color:'#ec4899',
    description:'DNA, heredity, Mendel\'s laws and evolution.',
    topics:[
      {id:'sbg1',name:'DNA Structure',notes:'<p>Double helix. Sugar-phosphate backbone. Base pairs: A-T, G-C. Genes are segments of DNA coding for proteins.</p>'},
      {id:'sbg2',name:'Mendel\'s Laws',notes:'<p>Law of Dominance, Law of Segregation, Law of Independent Assortment. Punnett squares for predicting offspring.</p>'},
      {id:'sbg3',name:'Heredity & Variation',notes:'<p>Traits passed from parents to offspring. Genotype vs Phenotype. Dominant vs Recessive alleles. Sex determination: XX/XY.</p>'},
      {id:'sbg4',name:'Evolution',notes:'<p>Darwin\'s natural selection. Evidence: fossils, homologous structures, DNA. Speciation. Adaptation over generations.</p>'},
      {id:'sbg5',name:'Genetic Disorders',notes:'<p>Chromosomal: Down syndrome. Single gene: sickle cell, cystic fibrosis, hemophilia. Genetic counseling and testing.</p>'},
    ]},
  { id:'s-bio-env', subject:'Biology', name:'Environmental Science Course', icon:'🌍', color:'#ec4899',
    description:'Ecosystems, biodiversity and environmental issues.',
    topics:[
      {id:'sbe1',name:'Ecosystems',notes:'<p>Biotic + Abiotic factors. Food chains and food webs. Energy flow: producers → consumers → decomposers. Trophic levels.</p>'},
      {id:'sbe2',name:'Biodiversity',notes:'<p>Variety of life forms. Hotspots. Endangered species. Conservation: in-situ (national parks) and ex-situ (zoos, seed banks).</p>'},
      {id:'sbe3',name:'Pollution',notes:'<p>Air (CO₂, SO₂), Water (industrial waste), Soil (pesticides), Noise pollution. Effects on health and ecosystems.</p>'},
      {id:'sbe4',name:'Natural Resources',notes:'<p>Renewable (solar, wind) vs Non-renewable (coal, oil). Sustainable development. 3 R\'s: Reduce, Reuse, Recycle.</p>'},
      {id:'sbe5',name:'Climate Change',notes:'<p>Greenhouse effect. Global warming causes. Effects: sea level rise, extreme weather. Mitigation: clean energy, reforestation.</p>'},
    ]},
  { id:'s-bio-cell', subject:'Biology', name:'Cell Biology Course', icon:'🔬', color:'#ec4899',
    description:'Cell structure, division and cellular processes.',
    topics:[
      {id:'sbc1',name:'Cell Structure',notes:'<p>Prokaryotic (no nucleus) vs Eukaryotic. Organelles: nucleus, mitochondria, ER, Golgi, lysosomes. Cell membrane: selectively permeable.</p>'},
      {id:'sbc2',name:'Cell Division',notes:'<p>Mitosis: growth/repair, 2 identical cells. Meiosis: gamete formation, 4 haploid cells. Stages: prophase, metaphase, anaphase, telophase.</p>'},
      {id:'sbc3',name:'Cell Transport',notes:'<p>Diffusion, Osmosis (water through semi-permeable membrane), Active transport (against gradient, requires ATP).</p>'},
      {id:'sbc4',name:'Cellular Respiration',notes:'<p>C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Glycolysis → Krebs cycle → Electron transport chain. Aerobic vs anaerobic.</p>'},
      {id:'sbc5',name:'Cell Specialization',notes:'<p>Stem cells can differentiate. Specialized cells: nerve, muscle, red blood, epithelial. Tissues → Organs → Systems.</p>'},
    ]},

  // ── Computer Science ──
  { id:'s-cs-fundamentals', subject:'Computer Science', name:'Computer Fundamentals Course', icon:'💻', color:'#06b6d4',
    description:'Hardware, software, number systems and networking basics.',
    topics:[
      {id:'scf1',name:'Computer Hardware',notes:'<p>Input (keyboard, mouse), Output (monitor, printer), Process (CPU), Storage (HDD, SSD, RAM, ROM). Motherboard connects all.</p>'},
      {id:'scf2',name:'Computer Software',notes:'<p>System software (OS, drivers) vs Application software (browser, office). Types of OS: Windows, Linux, macOS.</p>'},
      {id:'scf3',name:'Number Systems',notes:'<p>Binary (base 2), Octal (base 8), Decimal (base 10), Hexadecimal (base 16). Conversions between systems.</p>'},
      {id:'scf4',name:'Computer Memory',notes:'<p>Primary: RAM (volatile), ROM (non-volatile). Secondary: HDD, SSD, USB. Cache memory. Memory hierarchy.</p>'},
      {id:'scf5',name:'Networking Basics',notes:'<p>LAN, WAN, MAN. Protocols: TCP/IP, HTTP. IP addresses. Client-server model. Internet vs Intranet.</p>'},
    ]},
  { id:'s-cs-intro-prog', subject:'Computer Science', name:'Introduction to Programming Course', icon:'⌨️', color:'#06b6d4',
    description:'Programming concepts, flowcharts and pseudocode.',
    topics:[
      {id:'scp_1',name:'What is Programming',notes:'<p>Instructions to a computer. High-level vs low-level languages. Compilation vs interpretation. IDE usage.</p>'},
      {id:'scp_2',name:'Flowcharts & Pseudocode',notes:'<p>Flowcharts use symbols (oval=start/end, rectangle=process, diamond=decision). Pseudocode: English-like algorithm description.</p>'},
      {id:'scp_3',name:'Variables & Data Types',notes:'<p>Variables store data. Types: integer, float, string, boolean. Naming conventions. Constants vs variables.</p>'},
      {id:'scp_4',name:'Control Structures',notes:'<p>Sequential, Selection (if-else), Iteration (for, while loops). Nested conditions. Break and continue.</p>'},
      {id:'scp_5',name:'Functions & Procedures',notes:'<p>Reusable code blocks. Parameters and return values. Scope. Advantages: modularity, reusability, readability.</p>'},
    ]},
  { id:'s-cs-python', subject:'Computer Science', name:'Python for Beginners Course', icon:'🐍', color:'#06b6d4',
    description:'Learn Python programming from scratch.',
    topics:[
      {id:'spy1',name:'Python Basics',notes:'<p>Print, input, comments. Variables (no type declaration). Indentation matters. Interactive mode vs script mode.</p>'},
      {id:'spy2',name:'Data Types & Operators',notes:'<p>int, float, str, bool, list, tuple, dict. Arithmetic, comparison, logical, assignment operators.</p>'},
      {id:'spy3',name:'Control Flow',notes:'<p>if-elif-else. for loops (range, iterating). while loops. break, continue, pass. List comprehensions.</p>'},
      {id:'spy4',name:'Functions in Python',notes:'<p>def keyword. Parameters, default values, *args, **kwargs. Return values. Lambda functions. Built-in functions.</p>'},
      {id:'spy5',name:'Lists & Dictionaries',notes:'<p>Lists: ordered, mutable. Methods: append, pop, sort. Dictionaries: key-value pairs. Iteration and comprehension.</p>'},
    ]},
  { id:'s-cs-web', subject:'Computer Science', name:'Web Basics (HTML/CSS) Course', icon:'🌐', color:'#06b6d4',
    description:'Build web pages with HTML and CSS.',
    topics:[
      {id:'swb1',name:'HTML Basics',notes:'<p>Tags: html, head, body, h1-h6, p, a, img, div, span. Attributes: class, id, href, src. Document structure.</p>'},
      {id:'swb2',name:'HTML Forms & Tables',notes:'<p>Forms: input types (text, password, email, submit). Tables: table, tr, th, td. Semantic HTML: header, nav, main, footer.</p>'},
      {id:'swb3',name:'CSS Basics',notes:'<p>Selectors, properties, values. Inline, internal, external CSS. Colors, fonts, backgrounds. Box model: margin, border, padding, content.</p>'},
      {id:'swb4',name:'CSS Layout',notes:'<p>Display: block, inline, flex, grid. Positioning: static, relative, absolute, fixed. Responsive design with media queries.</p>'},
      {id:'swb5',name:'Building a Webpage',notes:'<p>Combining HTML + CSS. Project: personal portfolio page. Navigation, hero section, content cards, footer.</p>'},
    ]},
  { id:'s-cs-cyber', subject:'Computer Science', name:'Cyber Safety Course', icon:'🛡️', color:'#06b6d4',
    description:'Online safety, privacy and digital citizenship.',
    topics:[
      {id:'scy1',name:'Internet Safety',notes:'<p>Strong passwords, 2FA. Recognizing phishing. Safe browsing. Public Wi-Fi risks. Software updates importance.</p>'},
      {id:'scy2',name:'Social Media Safety',notes:'<p>Privacy settings. Cyberbullying awareness. Digital footprint. Sharing limits. Reporting mechanisms.</p>'},
      {id:'scy3',name:'Data Privacy',notes:'<p>Personal data protection. Cookies and tracking. GDPR basics. Reading privacy policies. Encryption basics.</p>'},
      {id:'scy4',name:'Malware & Threats',notes:'<p>Viruses, worms, trojans, ransomware, spyware. Antivirus software. Firewalls. Safe download practices.</p>'},
      {id:'scy5',name:'Ethical Computing',notes:'<p>Software piracy. Copyright and fair use. Creative Commons. Plagiarism. Responsible technology usage.</p>'},
    ]},

  // ── Social Science ──
  { id:'s-ss-history', subject:'Social Science', name:'World History Course', icon:'📜', color:'#a855f7',
    description:'Major historical events and civilizations.',
    topics:[
      {id:'ssh1',name:'Ancient Civilizations',notes:'<p>Mesopotamia, Egypt, Indus Valley, China. Agriculture revolution. Writing systems. Trade routes.</p>'},
      {id:'ssh2',name:'Medieval Period',notes:'<p>Feudalism, Crusades, Renaissance. Byzantine Empire. Islamic Golden Age. Mongol Empire expansion.</p>'},
      {id:'ssh3',name:'Modern Revolutions',notes:'<p>American Revolution, French Revolution, Industrial Revolution. Impact on society, governance and economy.</p>'},
      {id:'ssh4',name:'World Wars',notes:'<p>WWI: alliances, trench warfare. WWII: causes, Holocaust, atomic bombs. United Nations formation. Cold War.</p>'},
      {id:'ssh5',name:'Post-War World',notes:'<p>Decolonization. Cold War tensions. Space race. Globalization. Rise of technology. Contemporary challenges.</p>'},
    ]},
  { id:'s-ss-geography', subject:'Social Science', name:'Geography & Earth Science Course', icon:'🗺️', color:'#a855f7',
    description:'Earth\'s features, climate and natural phenomena.',
    topics:[
      {id:'ssg1',name:'Earth\'s Structure',notes:'<p>Layers: crust, mantle, outer core, inner core. Plate tectonics. Continental drift. Rock cycle: igneous, sedimentary, metamorphic.</p>'},
      {id:'ssg2',name:'Climate & Weather',notes:'<p>Weather: short-term conditions. Climate: long-term patterns. Factors: latitude, altitude, ocean currents. Climate zones.</p>'},
      {id:'ssg3',name:'Natural Disasters',notes:'<p>Earthquakes (seismic waves, Richter scale), Volcanoes, Tsunamis, Hurricanes, Floods. Disaster preparedness.</p>'},
      {id:'ssg4',name:'Maps & Navigation',notes:'<p>Latitude and longitude. Scale, legend, compass directions. Topographic maps. GIS and GPS technology.</p>'},
      {id:'ssg5',name:'Resources & Conservation',notes:'<p>Renewable vs non-renewable resources. Water cycle. Deforestation. Soil erosion. Sustainable development goals.</p>'},
    ]},
  { id:'s-ss-civics', subject:'Social Science', name:'Civics & Government Course', icon:'🏛️', color:'#a855f7',
    description:'Government systems, rights and responsibilities.',
    topics:[
      {id:'ssc1',name:'Types of Government',notes:'<p>Democracy, Monarchy, Dictatorship, Republic, Federation. Separation of powers: Legislature, Executive, Judiciary.</p>'},
      {id:'ssc2',name:'Constitution & Rights',notes:'<p>Written vs unwritten. Fundamental rights. Directive principles. Duties of citizens. Amendments process.</p>'},
      {id:'ssc3',name:'Elections & Voting',notes:'<p>Electoral process. Universal suffrage. First-past-the-post vs proportional representation. Role of election commission.</p>'},
      {id:'ssc4',name:'Local Government',notes:'<p>Municipal corporations, panchayats. Decentralization. Services: water, sanitation, roads. Citizen participation.</p>'},
      {id:'ssc5',name:'International Organizations',notes:'<p>UN, WHO, UNESCO, WTO, IMF, World Bank. Regional organizations. Peacekeeping. Human rights advocacy.</p>'},
    ]},
  { id:'s-ss-economics', subject:'Social Science', name:'Economics Basics Course', icon:'💰', color:'#a855f7',
    description:'Supply, demand, markets and economic systems.',
    topics:[
      {id:'sse1',name:'Introduction to Economics',notes:'<p>Scarcity and choice. Microeconomics vs macroeconomics. Factors of production: land, labor, capital, entrepreneurship.</p>'},
      {id:'sse2',name:'Supply & Demand',notes:'<p>Law of demand (price ↑, quantity ↓). Law of supply (price ↑, quantity ↑). Equilibrium price. Market forces.</p>'},
      {id:'sse3',name:'Money & Banking',notes:'<p>Functions of money: medium of exchange, unit of account, store of value. Banks: deposits, loans, interest. Central bank role.</p>'},
      {id:'sse4',name:'Economic Systems',notes:'<p>Capitalism (free market), Socialism (government control), Mixed economy. Pros and cons of each system.</p>'},
      {id:'sse5',name:'Globalization',notes:'<p>International trade. Imports/exports. MNCs. Trade agreements. Impact on developing countries. Fair trade.</p>'},
    ]},
];
