// ===== University-Level Course Data =====
export const UNI_COURSES = [
  // ── Programming ──
  {id:'u-prog-c',subject:'Programming',name:'C Programming Complete Course',icon:'©️',color:'#3b82f6',description:'Master C from basics to advanced pointers and file handling.',topics:[
    {id:'upc1',name:'C Basics & Syntax',notes:'<p>Data types: int, float, char, double. printf/scanf. Operators. Header files. Compilation process: preprocessing → compilation → assembly → linking.</p>'},
    {id:'upc2',name:'Control Flow in C',notes:'<p>if-else, switch-case, for, while, do-while, break, continue, goto. Nested loops. Ternary operator.</p>'},
    {id:'upc3',name:'Functions in C',notes:'<p>Declaration, definition, calling. Pass by value vs pass by reference. Recursion. Storage classes: auto, static, extern, register.</p>'},
    {id:'upc4',name:'Arrays & Strings',notes:'<p>1D and 2D arrays. String functions: strlen, strcpy, strcat, strcmp. Character arrays vs string.h library.</p>'},
    {id:'upc5',name:'Pointers',notes:'<p>Address-of (&) and dereference (*). Pointer arithmetic. Pointers to arrays, functions. Double pointers. Dynamic memory: malloc, calloc, realloc, free.</p>'},
    {id:'upc6',name:'Structures & File I/O',notes:'<p>struct, typedef, union. Nested structures. File operations: fopen, fclose, fprintf, fscanf, fread, fwrite. Binary vs text files.</p>'},
  ]},
  {id:'u-prog-cpp',subject:'Programming',name:'C++ Programming Course',icon:'➕',color:'#3b82f6',description:'Object-oriented programming with C++.',topics:[
    {id:'ucpp1',name:'C++ Fundamentals',notes:'<p>C++ extends C. cin/cout, namespaces, references. Default arguments. Function overloading. Inline functions.</p>'},
    {id:'ucpp2',name:'Classes & Objects',notes:'<p>Class definition, access specifiers (public, private, protected). Constructors, destructors. this pointer. Static members.</p>'},
    {id:'ucpp3',name:'Inheritance & Polymorphism',notes:'<p>Single, multiple, multilevel, hierarchical inheritance. Virtual functions, pure virtual. Abstract classes. Function overriding.</p>'},
    {id:'ucpp4',name:'Operator Overloading',notes:'<p>Overloading +, -, <<, >>. Friend functions. Type conversion. Rules and restrictions of operator overloading.</p>'},
    {id:'ucpp5',name:'Templates & STL',notes:'<p>Function and class templates. STL containers: vector, list, map, set, stack, queue. Iterators. Algorithms: sort, find, count.</p>'},
    {id:'ucpp6',name:'Exception Handling',notes:'<p>try, catch, throw. Multiple catch blocks. Custom exceptions. Stack unwinding. Best practices for error handling.</p>'},
  ]},
  {id:'u-prog-java',subject:'Programming',name:'Java Programming Course',icon:'☕',color:'#3b82f6',description:'Enterprise-grade OOP with Java.',topics:[
    {id:'uj1',name:'Java Basics',notes:'<p>JVM, JRE, JDK. Data types, variables. Scanner for input. String class. Arrays. Type casting. Wrapper classes.</p>'},
    {id:'uj2',name:'OOP in Java',notes:'<p>Classes, objects, constructors. Encapsulation (getters/setters). Inheritance (extends). Polymorphism. Abstraction (abstract, interface).</p>'},
    {id:'uj3',name:'Collections Framework',notes:'<p>List (ArrayList, LinkedList), Set (HashSet, TreeSet), Map (HashMap, TreeMap). Iterator. Comparable vs Comparator.</p>'},
    {id:'uj4',name:'Exception Handling',notes:'<p>try-catch-finally. Checked vs unchecked exceptions. throw and throws. Custom exceptions. Best practices.</p>'},
    {id:'uj5',name:'Multithreading',notes:'<p>Thread class, Runnable interface. Thread lifecycle. Synchronization. wait(), notify(). Thread pool. Concurrent collections.</p>'},
    {id:'uj6',name:'File I/O & Streams',notes:'<p>Byte streams, Character streams. BufferedReader, FileWriter. Serialization. Java NIO. Stream API (Java 8+): map, filter, reduce.</p>'},
  ]},
  {id:'u-prog-python',subject:'Programming',name:'Python Advanced Course',icon:'🐍',color:'#3b82f6',description:'Advanced Python: OOP, decorators, generators and more.',topics:[
    {id:'upa1',name:'OOP in Python',notes:'<p>Classes, __init__, self. Inheritance, multiple inheritance, MRO. Encapsulation (_ and __). @property. Magic methods (__str__, __repr__, __len__).</p>'},
    {id:'upa2',name:'Decorators & Generators',notes:'<p>First-class functions. Closures. @decorator syntax. functools.wraps. Generator functions (yield). Generator expressions. Lazy evaluation.</p>'},
    {id:'upa3',name:'File Handling & Modules',notes:'<p>open(), read(), write(), with statement. CSV, JSON handling. Creating modules and packages. __init__.py. pip and virtual environments.</p>'},
    {id:'upa4',name:'Error Handling & Testing',notes:'<p>try/except/else/finally. Custom exceptions. assert. unittest module. pytest. Test-driven development basics.</p>'},
    {id:'upa5',name:'Advanced Data Structures',notes:'<p>Collections: namedtuple, deque, Counter, defaultdict, OrderedDict. Heapq. Itertools: permutations, combinations, chain.</p>'},
    {id:'upa6',name:'Concurrency',notes:'<p>Threading vs multiprocessing. GIL. asyncio and async/await. Concurrent.futures. Thread pools. Process pools.</p>'},
  ]},

  // ── Core Computer Science ──
  {id:'u-cs-ds',subject:'Core CS',name:'Data Structures Complete Course',icon:'🏗️',color:'#06b6d4',description:'Master all fundamental data structures.',topics:[
    {id:'uds1',name:'Arrays & Linked Lists',notes:'<p>Static vs dynamic arrays. Singly, doubly, circular linked lists. Operations: insert, delete, search, reverse. Time complexities.</p>'},
    {id:'uds2',name:'Stacks & Queues',notes:'<p>Stack: LIFO. Queue: FIFO. Implementations using arrays and linked lists. Circular queue, deque, priority queue.</p>'},
    {id:'uds3',name:'Trees & BST',notes:'<p>Binary tree, BST, AVL tree. Traversals: inorder, preorder, postorder, level-order. Insert, delete, search in BST. Balancing.</p>'},
    {id:'uds4',name:'Heaps & Hashing',notes:'<p>Min-heap, max-heap. Heapify, extract. Priority queue. Hash tables, collision resolution: chaining, open addressing.</p>'},
    {id:'uds5',name:'Graphs',notes:'<p>Representations: adjacency matrix/list. BFS, DFS. Connected components. Topological sort. Cycle detection.</p>'},
    {id:'uds6',name:'Advanced Trees',notes:'<p>Red-Black trees, B-trees, B+ trees, Trie, Segment tree, Fenwick tree. Applications in databases and string processing.</p>'},
  ]},
  {id:'u-cs-algo',subject:'Core CS',name:'Algorithms Design Course',icon:'⚡',color:'#06b6d4',description:'Algorithm paradigms: sorting, searching, DP and greedy.',topics:[
    {id:'ual1',name:'Sorting Algorithms',notes:'<p>Bubble, Selection, Insertion (O(n²)). Merge Sort, Quick Sort (O(n log n)). Counting, Radix Sort (O(n)). Stability and in-place.</p>'},
    {id:'ual2',name:'Searching Algorithms',notes:'<p>Linear search O(n). Binary search O(log n). Ternary search. Interpolation search. Search in rotated arrays.</p>'},
    {id:'ual3',name:'Divide & Conquer',notes:'<p>Break into subproblems, solve recursively, combine. Examples: merge sort, quick sort, binary search, matrix multiplication.</p>'},
    {id:'ual4',name:'Dynamic Programming',notes:'<p>Overlapping subproblems + optimal substructure. Memoization vs tabulation. Classic: Fibonacci, Knapsack, LCS, LIS, coin change.</p>'},
    {id:'ual5',name:'Greedy Algorithms',notes:'<p>Make locally optimal choice at each step. Activity selection, Huffman coding, fractional knapsack, Dijkstra\'s, Kruskal\'s.</p>'},
    {id:'ual6',name:'Graph Algorithms',notes:'<p>Shortest path: Dijkstra, Bellman-Ford, Floyd-Warshall. MST: Prim, Kruskal. Network flow. Strongly connected components.</p>'},
  ]},
  {id:'u-cs-os',subject:'Core CS',name:'Operating Systems Course',icon:'🖥️',color:'#06b6d4',description:'Process, memory, file management and concurrency.',topics:[
    {id:'uos1',name:'Process Management',notes:'<p>Process states, PCB. Context switching. Scheduling: FCFS, SJF, Priority, Round Robin, MLFQ. Threads vs processes.</p>'},
    {id:'uos2',name:'Process Synchronization',notes:'<p>Critical section. Mutex, semaphores, monitors. Producer-consumer, readers-writers, dining philosophers problems.</p>'},
    {id:'uos3',name:'Deadlocks',notes:'<p>Conditions: mutual exclusion, hold-wait, no preemption, circular wait. Prevention, avoidance (Banker\'s), detection, recovery.</p>'},
    {id:'uos4',name:'Memory Management',notes:'<p>Paging, segmentation. Virtual memory. Page replacement: FIFO, LRU, Optimal. Thrashing. Working set model. TLB.</p>'},
    {id:'uos5',name:'File Systems',notes:'<p>File allocation: contiguous, linked, indexed. Directory structures. Free space management. Journaling. RAID levels.</p>'},
    {id:'uos6',name:'I/O & Disk Scheduling',notes:'<p>I/O types: programmed, interrupt-driven, DMA. Disk scheduling: FCFS, SSTF, SCAN, C-SCAN, LOOK. SSD considerations.</p>'},
  ]},
  {id:'u-cs-dbms',subject:'Core CS',name:'Database Management Systems Course',icon:'🗄️',color:'#06b6d4',description:'Relational databases, SQL and transaction management.',topics:[
    {id:'udb1',name:'ER Model & Relational Model',notes:'<p>Entities, attributes, relationships. Cardinality. ER diagrams. Relational model: tuples, attributes, keys. Schema design.</p>'},
    {id:'udb2',name:'SQL Mastery',notes:'<p>DDL, DML, DCL, TCL. Joins: inner, outer, cross, self. Subqueries. Aggregation: GROUP BY, HAVING. Views, indexes.</p>'},
    {id:'udb3',name:'Normalization',notes:'<p>Functional dependencies. 1NF → 2NF → 3NF → BCNF → 4NF. Decomposition. Lossless join. Dependency preservation.</p>'},
    {id:'udb4',name:'Transactions & Concurrency',notes:'<p>ACID properties. Serializability. Two-phase locking. Timestamp ordering. MVCC. Isolation levels. Deadlock in DBMS.</p>'},
    {id:'udb5',name:'Indexing & Query Optimization',notes:'<p>B-tree, B+ tree, hash indexes. Query execution plans. Join algorithms: nested loop, sort-merge, hash join. Query optimizer.</p>'},
    {id:'udb6',name:'NoSQL & Distributed DB',notes:'<p>CAP theorem. Types: document (MongoDB), key-value (Redis), column (Cassandra), graph (Neo4j). Sharding, replication.</p>'},
  ]},
  {id:'u-cs-cn',subject:'Core CS',name:'Computer Networks Course',icon:'🌐',color:'#06b6d4',description:'OSI model, TCP/IP, routing and network security.',topics:[
    {id:'ucn1',name:'Network Models',notes:'<p>OSI 7 layers vs TCP/IP 4 layers. Functions of each layer. Protocols at each layer. Encapsulation and decapsulation.</p>'},
    {id:'ucn2',name:'Data Link Layer',notes:'<p>Framing, error detection (CRC, checksum), error correction. Flow control: stop-and-wait, sliding window. MAC protocols: CSMA/CD.</p>'},
    {id:'ucn3',name:'Network Layer',notes:'<p>IP addressing (IPv4, IPv6). Subnetting, CIDR. Routing: RIP, OSPF, BGP. NAT. ICMP. ARP. Fragmentation.</p>'},
    {id:'ucn4',name:'Transport Layer',notes:'<p>TCP: connection-oriented, reliable, flow/congestion control. UDP: connectionless. Port numbers. Three-way handshake.</p>'},
    {id:'ucn5',name:'Application Layer',notes:'<p>HTTP/HTTPS, FTP, SMTP, DNS, DHCP. REST APIs. Sockets programming. Client-server vs P2P architectures.</p>'},
    {id:'ucn6',name:'Network Security',notes:'<p>Symmetric vs asymmetric encryption. Digital signatures. SSL/TLS. Firewalls. VPN. Attacks: DDoS, MITM, spoofing.</p>'},
  ]},

  // ── AI / ML ──
  {id:'u-ai-intro',subject:'AI / ML',name:'Introduction to Artificial Intelligence',icon:'🤖',color:'#a855f7',description:'Foundations of AI: search, logic and knowledge.',topics:[
    {id:'uai1',name:'What is AI?',notes:'<p>History: Turing test, Dartmouth conference. Types: Narrow AI, General AI, Super AI. Applications: NLP, vision, robotics.</p>'},
    {id:'uai2',name:'Search Algorithms',notes:'<p>Uninformed: BFS, DFS, iterative deepening. Informed: A*, greedy best-first. Heuristics. Adversarial search: minimax, alpha-beta pruning.</p>'},
    {id:'uai3',name:'Knowledge Representation',notes:'<p>Propositional logic, first-order logic. Inference rules. Ontologies. Semantic networks. Frames and scripts.</p>'},
    {id:'uai4',name:'Probabilistic Reasoning',notes:'<p>Bayes\' theorem. Bayesian networks. Hidden Markov Models. Uncertainty handling. Decision theory.</p>'},
    {id:'uai5',name:'Planning & Agents',notes:'<p>Intelligent agents: simple reflex, model-based, goal-based, utility-based. STRIPS planning. Reinforcement learning intro.</p>'},
  ]},
  {id:'u-ai-ml',subject:'AI / ML',name:'Machine Learning Course',icon:'📈',color:'#a855f7',description:'Supervised, unsupervised and reinforcement learning.',topics:[
    {id:'uml1',name:'ML Fundamentals',notes:'<p>Types: supervised, unsupervised, reinforcement. Training/testing split. Overfitting vs underfitting. Bias-variance tradeoff. Cross-validation.</p>'},
    {id:'uml2',name:'Regression',notes:'<p>Linear regression, polynomial regression. Cost function (MSE). Gradient descent. Regularization: L1 (Lasso), L2 (Ridge). R² score.</p>'},
    {id:'uml3',name:'Classification',notes:'<p>Logistic regression, decision trees, random forests, SVM, KNN, Naive Bayes. Evaluation: accuracy, precision, recall, F1, ROC-AUC.</p>'},
    {id:'uml4',name:'Unsupervised Learning',notes:'<p>K-Means clustering, hierarchical clustering, DBSCAN. PCA for dimensionality reduction. Association rules: Apriori algorithm.</p>'},
    {id:'uml5',name:'Ensemble Methods',notes:'<p>Bagging (Random Forest), Boosting (AdaBoost, Gradient Boosting, XGBoost). Stacking. Why ensembles work: diversity reduces error.</p>'},
    {id:'uml6',name:'Model Selection & Tuning',notes:'<p>Hyperparameter tuning: grid search, random search. Feature engineering and selection. Pipeline. MLOps basics.</p>'},
  ]},
  {id:'u-ai-dl',subject:'AI / ML',name:'Deep Learning Course',icon:'🧠',color:'#a855f7',description:'Neural networks, CNNs, RNNs and transformers.',topics:[
    {id:'udl1',name:'Neural Network Basics',notes:'<p>Perceptron, activation functions (ReLU, sigmoid, tanh, softmax). Forward propagation. Loss functions. Backpropagation.</p>'},
    {id:'udl2',name:'Training Deep Networks',notes:'<p>Optimizers: SGD, Adam, RMSprop. Learning rate scheduling. Batch normalization. Dropout. Weight initialization.</p>'},
    {id:'udl3',name:'CNNs',notes:'<p>Convolution, pooling, stride, padding. Architectures: LeNet, AlexNet, VGG, ResNet. Transfer learning. Image classification.</p>'},
    {id:'udl4',name:'RNNs & LSTMs',notes:'<p>Sequence modeling. Vanishing gradient problem. LSTM gates: forget, input, output. GRU. Bidirectional RNNs. Seq2Seq.</p>'},
    {id:'udl5',name:'Transformers & Attention',notes:'<p>Self-attention mechanism. Multi-head attention. Positional encoding. BERT, GPT architecture. Pre-training and fine-tuning.</p>'},
    {id:'udl6',name:'GANs & Autoencoders',notes:'<p>Generator vs discriminator. Training dynamics. Variational autoencoders (VAE). Applications: image generation, style transfer.</p>'},
  ]},
  {id:'u-ai-nlp',subject:'AI / ML',name:'Natural Language Processing Course',icon:'💬',color:'#a855f7',description:'Text processing, embeddings and language models.',topics:[
    {id:'unl1',name:'Text Preprocessing',notes:'<p>Tokenization, stemming, lemmatization. Stop words. TF-IDF. Bag of words. N-grams. Regular expressions for text.</p>'},
    {id:'unl2',name:'Word Embeddings',notes:'<p>Word2Vec (CBOW, Skip-gram). GloVe. FastText. Embedding layers. Dimensionality and semantic similarity.</p>'},
    {id:'unl3',name:'Text Classification',notes:'<p>Sentiment analysis, spam detection. Naive Bayes, SVM, LSTM for text. Evaluation metrics. Dataset handling: IMDB, AG News.</p>'},
    {id:'unl4',name:'Sequence Models for NLP',notes:'<p>RNN/LSTM for text. Attention mechanism. Machine translation. Beam search decoding. BLEU score.</p>'},
    {id:'unl5',name:'Modern NLP',notes:'<p>Transformer-based models: BERT, GPT, T5. Hugging Face library. Fine-tuning. Prompt engineering. Few-shot learning.</p>'},
  ]},
  {id:'u-ai-cv',subject:'AI / ML',name:'Computer Vision Course',icon:'👁️',color:'#a855f7',description:'Image processing, detection and segmentation.',topics:[
    {id:'ucv1',name:'Image Fundamentals',notes:'<p>Pixels, color spaces (RGB, HSV, grayscale). Image filtering. Edge detection: Sobel, Canny. Histogram equalization.</p>'},
    {id:'ucv2',name:'Feature Detection',notes:'<p>Harris corner detector, SIFT, SURF, ORB. Feature matching. Homography. Image stitching (panorama).</p>'},
    {id:'ucv3',name:'Object Detection',notes:'<p>Sliding window, selective search. R-CNN family. YOLO, SSD. Anchor boxes. Non-max suppression. mAP evaluation.</p>'},
    {id:'ucv4',name:'Image Segmentation',notes:'<p>Semantic vs instance vs panoptic segmentation. U-Net, FCN, Mask R-CNN. DeepLab. Medical imaging applications.</p>'},
    {id:'ucv5',name:'Video Analysis & 3D Vision',notes:'<p>Optical flow, object tracking. Action recognition. 3D reconstruction. Depth estimation. Point clouds.</p>'},
  ]},

  // ── Web Development ──
  {id:'u-web-fullstack',subject:'Web Development',name:'Full Stack Web Development Course',icon:'🌐',color:'#f59e0b',description:'End-to-end web development: frontend, backend, database.',topics:[
    {id:'uwf1',name:'Web Architecture',notes:'<p>Client-server model. HTTP methods (GET, POST, PUT, DELETE). REST principles. Status codes. DNS resolution. CDNs.</p>'},
    {id:'uwf2',name:'HTML5 & CSS3',notes:'<p>Semantic HTML. Flexbox, Grid layouts. CSS animations, transitions. Responsive design. CSS preprocessors: SASS.</p>'},
    {id:'uwf3',name:'JavaScript Essentials',notes:'<p>ES6+: let/const, arrow functions, destructuring, spread, promises, async/await. DOM manipulation. Event handling.</p>'},
    {id:'uwf4',name:'Backend Basics',notes:'<p>Node.js, Express.js setup. Routing, middleware. RESTful API design. Authentication: JWT, sessions. Environment variables.</p>'},
    {id:'uwf5',name:'Database Integration',notes:'<p>SQL (PostgreSQL/MySQL) vs NoSQL (MongoDB). ORMs: Sequelize, Mongoose. CRUD operations. Schema design. Migrations.</p>'},
    {id:'uwf6',name:'Deployment',notes:'<p>Git/GitHub workflow. CI/CD basics. Docker containers. Cloud: AWS/Heroku/Vercel. Domain, SSL, environment configs.</p>'},
  ]},
  {id:'u-web-frontend',subject:'Web Development',name:'Frontend Development Course',icon:'🎨',color:'#f59e0b',description:'Modern frontend: frameworks, state and tooling.',topics:[
    {id:'uwfe1',name:'Advanced CSS',notes:'<p>CSS Grid mastery. Custom properties. Animations and keyframes. Mobile-first design. BEM methodology. CSS-in-JS.</p>'},
    {id:'uwfe2',name:'JavaScript Deep Dive',notes:'<p>Closures, prototypes, this keyword. Event loop. Fetch API. Modules. Web APIs: localStorage, Intersection Observer.</p>'},
    {id:'uwfe3',name:'React Fundamentals',notes:'<p>Components, JSX, props, state. Hooks: useState, useEffect, useContext. Virtual DOM. Component lifecycle.</p>'},
    {id:'uwfe4',name:'State Management',notes:'<p>Context API, useReducer. Redux: store, actions, reducers. Redux Toolkit. Zustand. State management patterns.</p>'},
    {id:'uwfe5',name:'Build Tools & Testing',notes:'<p>Vite, Webpack. ESLint, Prettier. Jest, React Testing Library. E2E testing with Cypress. Performance optimization.</p>'},
  ]},
  {id:'u-web-backend',subject:'Web Development',name:'Backend Development Course',icon:'⚙️',color:'#f59e0b',description:'Server-side development with Node.js and databases.',topics:[
    {id:'uwbe1',name:'Node.js Fundamentals',notes:'<p>Event-driven, non-blocking I/O. Modules (CommonJS, ESM). npm ecosystem. File system API. Streams and buffers.</p>'},
    {id:'uwbe2',name:'Express.js Framework',notes:'<p>Routing, middleware chain. Request/response objects. Template engines. Error handling. Static file serving. CORS.</p>'},
    {id:'uwbe3',name:'Database Design',notes:'<p>Relational vs document databases. Schema design. Indexing. Transactions. Connection pooling. Data validation.</p>'},
    {id:'uwbe4',name:'Authentication & Security',notes:'<p>Password hashing (bcrypt). JWT tokens. OAuth 2.0. Session management. CSRF, XSS, SQL injection prevention. Rate limiting.</p>'},
    {id:'uwbe5',name:'API Design & Microservices',notes:'<p>RESTful best practices. GraphQL intro. API versioning. Microservices architecture. Message queues. Service discovery.</p>'},
  ]},
  {id:'u-web-react',subject:'Web Development',name:'React.js Mastery Course',icon:'⚛️',color:'#f59e0b',description:'Advanced React patterns and ecosystem.',topics:[
    {id:'uwr1',name:'React Core Concepts',notes:'<p>Functional components, hooks, JSX. Component composition. Prop drilling solutions. React.memo, useMemo, useCallback.</p>'},
    {id:'uwr2',name:'Advanced Hooks',notes:'<p>Custom hooks. useRef, useImperativeHandle. useDeferredValue, useTransition (React 18). Hook rules and patterns.</p>'},
    {id:'uwr3',name:'Routing & Forms',notes:'<p>React Router v6. Nested routes, dynamic segments. Form handling: controlled components, React Hook Form, Formik.</p>'},
    {id:'uwr4',name:'Data Fetching',notes:'<p>useEffect for fetching. SWR, React Query. Suspense for data. Optimistic updates. Caching strategies. Error boundaries.</p>'},
    {id:'uwr5',name:'Next.js & SSR',notes:'<p>Server-side rendering, static generation. App Router. Server components. API routes. Image optimization. Middleware.</p>'},
  ]},
  {id:'u-web-node',subject:'Web Development',name:'Node.js Course',icon:'💚',color:'#f59e0b',description:'Server-side JavaScript with Node.js ecosystem.',topics:[
    {id:'uwn1',name:'Node.js Architecture',notes:'<p>V8 engine, event loop, libuv. Single-threaded model. Worker threads. Cluster module for multi-core. Performance profiling.</p>'},
    {id:'uwn2',name:'Core Modules',notes:'<p>fs, path, os, http, crypto, stream, events. Buffer handling. Child processes. Timers and scheduling.</p>'},
    {id:'uwn3',name:'npm & Package Management',notes:'<p>package.json, semantic versioning. Dependencies vs devDependencies. npm scripts. Publishing packages. Monorepos.</p>'},
    {id:'uwn4',name:'Real-time Apps',notes:'<p>WebSockets with Socket.io. Server-sent events. Real-time chat application. Presence detection. Room management.</p>'},
    {id:'uwn5',name:'Testing & Debugging',notes:'<p>Mocha, Chai, Jest for Node. Supertest for API testing. Debugging: node inspect, VS Code debugger. Logging: Winston, Morgan.</p>'},
  ]},

  // ── App Development ──
  {id:'u-app-android',subject:'App Development',name:'Android App Development Course',icon:'📱',color:'#22c55e',description:'Native Android with Kotlin/Java.',topics:[
    {id:'uaa1',name:'Android Basics',notes:'<p>Android architecture. Activities, fragments. Layouts: LinearLayout, ConstraintLayout. Views and ViewGroups. Manifest file.</p>'},
    {id:'uaa2',name:'UI Design',notes:'<p>Material Design. RecyclerView, CardView. Navigation component. Themes and styles. Animations. Responsive layouts.</p>'},
    {id:'uaa3',name:'Data Storage',notes:'<p>SharedPreferences. SQLite with Room. Content providers. DataStore. File storage. Network caching strategies.</p>'},
    {id:'uaa4',name:'Networking',notes:'<p>Retrofit, OkHttp. JSON parsing: Gson, Moshi. REST API consumption. Image loading: Glide, Coil. Background tasks: WorkManager.</p>'},
    {id:'uaa5',name:'Architecture Patterns',notes:'<p>MVC, MVP, MVVM. ViewModel, LiveData. Repository pattern. Dependency injection: Hilt/Dagger. Clean architecture.</p>'},
    {id:'uaa6',name:'Publishing',notes:'<p>APK vs AAB. Signing. Google Play Console. Store listing optimization. Crash analytics: Firebase Crashlytics. CI/CD.</p>'},
  ]},
  {id:'u-app-flutter',subject:'App Development',name:'Flutter Development Course',icon:'🦋',color:'#22c55e',description:'Cross-platform apps with Flutter & Dart.',topics:[
    {id:'ufl1',name:'Dart Language',notes:'<p>Variables, types, functions. Null safety. Classes and mixins. Async: Future, Stream, async/await. Collections.</p>'},
    {id:'ufl2',name:'Flutter Widgets',notes:'<p>StatelessWidget vs StatefulWidget. Scaffold, AppBar, Container. Row, Column, Stack. ListView, GridView. Custom widgets.</p>'},
    {id:'ufl3',name:'State Management',notes:'<p>setState, InheritedWidget. Provider, Riverpod, Bloc pattern. State management comparison. Choosing the right approach.</p>'},
    {id:'ufl4',name:'Navigation & Routing',notes:'<p>Navigator 1.0 vs 2.0. Named routes. GoRouter. Bottom navigation. Drawer. Tab bar. Deep linking.</p>'},
    {id:'ufl5',name:'Firebase Integration',notes:'<p>Firebase Auth, Firestore, Storage, Cloud Messaging. Real-time data. Analytics. Remote Config. Crashlytics.</p>'},
  ]},
  {id:'u-app-rn',subject:'App Development',name:'React Native Course',icon:'📲',color:'#22c55e',description:'Mobile apps with React Native and Expo.',topics:[
    {id:'urn1',name:'React Native Basics',notes:'<p>Expo vs bare workflow. Core components: View, Text, Image, ScrollView. Styling with StyleSheet. Platform-specific code.</p>'},
    {id:'urn2',name:'Navigation',notes:'<p>React Navigation: stack, tab, drawer navigators. Nested navigation. Deep linking. Navigation state management.</p>'},
    {id:'urn3',name:'Native Modules',notes:'<p>Bridging native code. Camera, geolocation, push notifications. Linking libraries. Turbo modules (new architecture).</p>'},
    {id:'urn4',name:'State & Data',notes:'<p>Context, Redux, Zustand in RN. AsyncStorage. SQLite. React Query for remote data. Offline-first strategies.</p>'},
    {id:'urn5',name:'Building & Publishing',notes:'<p>EAS Build. Over-the-air updates. App Store and Play Store submission. CodePush. Performance optimization. Hermes engine.</p>'},
  ]},

  // ── Cybersecurity ──
  {id:'u-sec-ethical',subject:'Cybersecurity',name:'Ethical Hacking Course',icon:'🎯',color:'#ef4444',description:'Penetration testing and vulnerability assessment.',topics:[
    {id:'seh1',name:'Introduction to Ethical Hacking',notes:'<p>White hat vs black hat vs grey hat. Legal framework. Penetration testing methodology. Scope and rules of engagement.</p>'},
    {id:'seh2',name:'Reconnaissance',notes:'<p>Passive: OSINT, Google dorking, Shodan, social media. Active: port scanning (Nmap), service enumeration. footprinting.</p>'},
    {id:'seh3',name:'Vulnerability Analysis',notes:'<p>Vulnerability scanners: Nessus, OpenVAS. CVE database. OWASP Top 10. Common web vulnerabilities. Risk assessment.</p>'},
    {id:'seh4',name:'Exploitation',notes:'<p>Metasploit framework. Buffer overflows. SQL injection. XSS. CSRF. Privilege escalation. Post-exploitation.</p>'},
    {id:'seh5',name:'Reporting',notes:'<p>Writing penetration test reports. Executive summary. Technical findings. Risk ratings. Remediation recommendations.</p>'},
  ]},
  {id:'u-sec-fundamentals',subject:'Cybersecurity',name:'Cybersecurity Fundamentals Course',icon:'🔒',color:'#ef4444',description:'Core security concepts and defense strategies.',topics:[
    {id:'usf1',name:'Security Principles',notes:'<p>CIA triad: confidentiality, integrity, availability. Defense in depth. Least privilege. Zero trust architecture.</p>'},
    {id:'usf2',name:'Threats & Attacks',notes:'<p>Malware types. Social engineering: phishing, pretexting. DDoS attacks. Man-in-the-middle. Insider threats. APTs.</p>'},
    {id:'usf3',name:'Security Controls',notes:'<p>Preventive, detective, corrective controls. Firewalls, IDS/IPS. Antivirus. Access control models: DAC, MAC, RBAC.</p>'},
    {id:'usf4',name:'Incident Response',notes:'<p>IR lifecycle: preparation, identification, containment, eradication, recovery, lessons learned. SIEM tools. Digital forensics basics.</p>'},
    {id:'usf5',name:'Compliance & Standards',notes:'<p>ISO 27001, NIST framework, PCI-DSS, HIPAA, GDPR. Security policies. Risk management. Security audits.</p>'},
  ]},
  {id:'u-sec-network',subject:'Cybersecurity',name:'Network Security Course',icon:'🛡️',color:'#ef4444',description:'Securing networks, protocols and infrastructure.',topics:[
    {id:'usn1',name:'Network Security Basics',notes:'<p>Network threats landscape. Attack surfaces. Network segmentation. DMZ. VLANs. Network monitoring tools.</p>'},
    {id:'usn2',name:'Firewalls & VPN',notes:'<p>Packet filtering, stateful inspection, application-level firewalls. VPN protocols: IPSec, OpenVPN, WireGuard. Tunnel modes.</p>'},
    {id:'usn3',name:'Intrusion Detection',notes:'<p>IDS vs IPS. Signature-based vs anomaly-based detection. Snort, Suricata. SIEM integration. Alert management.</p>'},
    {id:'usn4',name:'Wireless Security',notes:'<p>WEP, WPA, WPA2, WPA3. Wireless attacks: deauth, evil twin. Secure wireless configuration. 802.1X authentication.</p>'},
    {id:'usn5',name:'Network Forensics',notes:'<p>Packet capture: Wireshark, tcpdump. Traffic analysis. Log analysis. Chain of custody. Evidence preservation.</p>'},
  ]},
  {id:'u-sec-crypto',subject:'Cybersecurity',name:'Cryptography Course',icon:'🔐',color:'#ef4444',description:'Encryption, hashing, digital signatures and PKI.',topics:[
    {id:'ucr1',name:'Cryptography Basics',notes:'<p>Plaintext, ciphertext, keys. Symmetric vs asymmetric. Historical ciphers: Caesar, Vigenère. Kerckhoffs\' principle.</p>'},
    {id:'ucr2',name:'Symmetric Encryption',notes:'<p>AES (block cipher), ChaCha20 (stream cipher). Modes: ECB, CBC, CTR, GCM. Key generation and management.</p>'},
    {id:'ucr3',name:'Asymmetric Encryption',notes:'<p>RSA algorithm. Diffie-Hellman key exchange. Elliptic curve cryptography (ECC). Key pairs. Digital envelopes.</p>'},
    {id:'ucr4',name:'Hashing & Digital Signatures',notes:'<p>SHA-256, SHA-3, bcrypt. Hash properties. HMAC. Digital signatures. Certificate authorities. X.509 certificates.</p>'},
    {id:'ucr5',name:'PKI & Applications',notes:'<p>Public Key Infrastructure. Certificate lifecycle. SSL/TLS handshake. HTTPS. Secure email (S/MIME, PGP). Blockchain basics.</p>'},
  ]},

  // ── Mathematics ──
  {id:'u-math-calc',subject:'Mathematics',name:'Calculus Course',icon:'∫',color:'#ec4899',description:'Limits, derivatives, integrals and applications.',topics:[
    {id:'umc1',name:'Limits & Continuity',notes:'<p>Definition of limits. L\'Hôpital\'s rule. One-sided limits. Continuity: IVT, EVT. Epsilon-delta definition.</p>'},
    {id:'umc2',name:'Derivatives',notes:'<p>Definition, power rule, product rule, quotient rule, chain rule. Implicit differentiation. Higher-order derivatives.</p>'},
    {id:'umc3',name:'Applications of Derivatives',notes:'<p>Rate of change, tangent lines. Maxima/minima. Mean value theorem. Curve sketching. Optimization problems.</p>'},
    {id:'umc4',name:'Integrals',notes:'<p>Antiderivatives. Definite vs indefinite integrals. Fundamental theorem. Techniques: substitution, parts, partial fractions.</p>'},
    {id:'umc5',name:'Applications of Integrals',notes:'<p>Area under curves, between curves. Volume of revolution (disk, shell). Arc length. Work and fluid force.</p>'},
    {id:'umc6',name:'Multivariable Calculus Intro',notes:'<p>Partial derivatives. Gradient. Double integrals. Vector fields. Line integrals. Green\'s theorem overview.</p>'},
  ]},
  {id:'u-math-la',subject:'Mathematics',name:'Linear Algebra Course',icon:'📐',color:'#ec4899',description:'Vectors, matrices, transformations and eigenvalues.',topics:[
    {id:'umla1',name:'Vectors & Vector Spaces',notes:'<p>Vectors in Rⁿ. Addition, scalar multiplication. Linear independence. Span. Basis and dimension. Subspaces.</p>'},
    {id:'umla2',name:'Matrices & Operations',notes:'<p>Matrix addition, multiplication. Transpose, trace. Special matrices: identity, diagonal, symmetric, orthogonal.</p>'},
    {id:'umla3',name:'Systems of Linear Equations',notes:'<p>Gaussian elimination. Row echelon form. Rank. Homogeneous systems. Inverse matrix method. Cramer\'s rule.</p>'},
    {id:'umla4',name:'Determinants',notes:'<p>2×2, 3×3 and general computation. Properties. Cofactor expansion. Applications: area, volume, invertibility.</p>'},
    {id:'umla5',name:'Eigenvalues & Eigenvectors',notes:'<p>Characteristic equation. Finding eigenvalues/vectors. Diagonalization. Applications: PCA, stability analysis, Markov chains.</p>'},
    {id:'umla6',name:'Linear Transformations',notes:'<p>Definition, kernel, image. Matrix representation. Rank-nullity theorem. Change of basis. Orthogonal projections.</p>'},
  ]},
  {id:'u-math-prob',subject:'Mathematics',name:'Probability & Statistics Course',icon:'🎲',color:'#ec4899',description:'Probability theory, distributions and hypothesis testing.',topics:[
    {id:'umps1',name:'Probability Theory',notes:'<p>Sample space, events. Axioms. Conditional probability. Bayes\' theorem. Independence. Law of total probability.</p>'},
    {id:'umps2',name:'Random Variables',notes:'<p>Discrete vs continuous. PMF, PDF, CDF. Expected value, variance. Moments. Moment generating functions.</p>'},
    {id:'umps3',name:'Distributions',notes:'<p>Binomial, Poisson, geometric (discrete). Normal, exponential, uniform (continuous). Central limit theorem.</p>'},
    {id:'umps4',name:'Statistical Inference',notes:'<p>Point estimation, interval estimation. Confidence intervals. Maximum likelihood. Method of moments. Sufficient statistics.</p>'},
    {id:'umps5',name:'Hypothesis Testing',notes:'<p>Null and alternative hypotheses. Type I and II errors. t-test, chi-squared test, ANOVA. p-values. Significance levels.</p>'},
    {id:'umps6',name:'Regression Analysis',notes:'<p>Simple linear regression. Least squares. R². Multiple regression. Residual analysis. Assumptions and diagnostics.</p>'},
  ]},
];
